---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Australia/Brisbane
  METALLB_LB_RANGE: 10.0.50.50-10.0.50.80
  METALLB_K8S_GATEWAY_ADDR: 10.0.50.55
  METALLB_INGRESS_ADDR: 10.0.50.50
