# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5+l1Babl4Aigog==,iv:8IMHANyiTtA257Tp39voEGWPKrV0EgAjsCqB0VJy5I0=,tag:c2jzrHZNnZGcW+BuoxSoHQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9COd0MxQA3dxKBW6Ewk6,iv:9MBOe/WC5BaMNZraebaHbIABa5373d3jIZq3OLQmWTI=,tag:SI8ScoXpiCpXcc3HP3RbdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY0llcXUvc3F6bXpSTmVR
            M0lva0lkakNlNWNIbG5YUWFwZ3dLQUFoZHhvCmo4aGFja20xZW5jVlErSzJ3am9S
            YXVDKzB2VHFCbi8raGwwa3hmb1hTVVkKLS0tIEZMSmprRjU1STlsUEV6ZWRYTWFJ
            d0dsU3dlSjdZQmdGanZBSUxFTWxFVncKkUfeAtdA5uMyv0WkYqy9vNmjffiCxosH
            clXq01hGRLHQx94rhGN/Ix6OfCFrxSa+GanEPDYBGmrONhKuiUBCPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T00:18:09Z"
    mac: ENC[AES256_GCM,data:xWPp7u+gJ8oYPwJzss14E1XJMhIGqr2SkpI+2W/9TtWLKpsJdFrFjPZ8d0IQU8k3qFCnmiO8EvVgoojdZWwrFeqyqeXWftVb6ausv/F539BWh56OMyG1SampdcWPiKatFUuxc/+nJhsJEKcC7NnrLWy2XSURGUWKvaUhPZnc+fc=,iv:cCpEyQxhAfG8hHgwPf4wEKEGZFpj63gao3Gh8P3DMlM=,tag:gPYLN5yj+GucKLIJ9APp/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
