# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:yjPRyTiNie5IuA==,iv:x5qxVhVf5dOexa9cbooqgbhk9PG82PrqDadza1++UV4=,tag:rL5C29HfFWy3ML04184krg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kDOBI3gxGHCqhbcTpN93,iv:ygcuZr4qJ/SwuaOcPfHPqUhqsCSz8uLQYfx2gJ4E5xI=,tag:POd0O6M2SFNagTAw16/CeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYWtJOFV5emd3UkorNVZh
            ZzkxYU4xN0tidDF2Wi9XRzdMZ1dkd2lQYjBnCnVnZUpwcjJiUndQNWpzOWcyZ2dI
            NlJ4NG1JcFByUm1RbWlRdWJNL2o3V0kKLS0tIFd6SmdYb1k1MWxndWZobE55NXNp
            ZXArZEc1Tmt3S2xvSW5IMzZoV01EZzQK/vn2hpmP3m7rL6lLtihbYOvVgYQcRaEh
            UGFXlUID3ldmPifvb9XTrgohaq9U8tNoXgjbIZFKlf8Ilz2/D1ULtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T04:26:00Z"
    mac: ENC[AES256_GCM,data:GDEaY0X69yuzo3t+QGwy+HIMjThnx6fm/z+padZMiBs98O5oA1Me6ryIUjUrfF5CHQZnjEpG7JMmZI+CrACsp4X4qPY9RjF9lZaEU90Fw1dGehFG8IMCLp++m8Vt3/TjSU1Qd6djSwsdynkqeQgQ/ZXD9vIK1qAH3LPU/IWRGTc=,iv:RjlC7GdSBS51/22/LBZpOPirnioEZ5Epz8xQGVwZtNs=,tag:gba8T9ZmnEajqGuThH0rPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
