kind: Secret
ansible_user: ENC[AES256_GCM,data:W9kuCBENxA==,iv:cYNZyffy/e2oucp+AxGsz0TTcCAIjpQhbuM3IF2r29s=,tag:AxIgQt2uQuikL0gjOIdGDA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AK60ksVnlZhXSd9F,iv:GP277FMjJaOPT0AR1mwJxU+2rXB4TWC5pr28ZXvSLt8=,tag:XKPmITaknnMrJa4pyhj0/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNU8rUTlvMzJKTnVOb2ky
            YkJiWDBkeDkzclVVK3F0SWxNbkxnZkhKd1RFCndiaEFkVFZvangxbS8rV1BueU9F
            YWFtR0JKWGF3Z2tRNDI0TWlUWGs2ajAKLS0tIEFkaXpXM3RNOVBBYlhIdWJTV2hx
            QjJQbkdmNWxWOVBvYlZVZkdrTXUxdWsKXOwg0vbZipO1dFNOO//isIQNy4M84TSg
            41gSOohkJb0F9xA2x8oUZj/CBOs+95i+X6+c1OSlM3NewTW9ieO8MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T00:18:09Z"
    mac: ENC[AES256_GCM,data:QimtSLLYlhcSCfq/mfTNrZX2HkvP5RP8lULFzKnrPpXVEOd8lGNbNy3/myUOF454UOkp7Ov1ZlF4UkxPOlF9TpRYg1ZGiXKrJBEio0C9OUg53MT5UxHJwLTOulSS5wQZjg9vGwIpLHGNCu0VAYEyObMEaZqs+c2XFEqV0YrC+DE=,iv:2WdvDa5jBLci66WOgEVxj9ig+5ATqegBi+TbLqHjkCc=,tag:HeKvwekMSvu+BHubxu5sig==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
