kind: Secret
ansible_user: ENC[AES256_GCM,data:JXkvXLGgdQ==,iv:G0XGei6m/Ay8/ltgLQXlxHzptdrjj2y360OpWjcv8VI=,tag:WT7tawS2gePIJWJcYC/dNw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2WYYUvSKylv4s5DB,iv:1k2hBApN6m/VIftF3XnQ+75QicOVdktpiKrCI7dlFKc=,tag:jI/kohNsKlCEg6ijMn+C3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc1N3b0dST3laYlpSU0tX
            bUVmVmRTTnVUa2VDYkU5YVQ3NkxGNzNleFZFCmx6dk9xcWZwOE42anBPNWx0a05p
            NjExaU95YnVibDNYRzM3WEw4ZkFwYUkKLS0tIHg3WVFlblE4ODFFZ3FrY3B4Z2ZU
            aU1FdE4zRE5uaG1HMTNid0pXOUgrVEkKW0IlQTYIhi7FBmEtBHf1MHOZE9ncHcQt
            RV/QAv9Lz7lyAMTQYmIYsLd2GcYw3bOTPECXbHAlNdwiqXX0zvyGww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T03:32:17Z"
    mac: ENC[AES256_GCM,data:nwt8qx70dogtUG7OIO6smUpxipDyh4I4ANsUwU6jmXgIg+aAm5lpUWBm8We/pE+Br3B16D7gMRP7c9lYPkQVVb0T6JeuSGofX8F2k+qAZ85Ys/GDPnXx49IjjCkoDYagJJdvodQKmpj5yKSuxA1Jji1hxG73wM9R59TpGuk0UuU=,iv:1CNyO/jKhU3Gp6eunsi6rGbxdQpVtc4jrRgSmgDj+gc=,tag:4WjLkmDhbm5ZkPFOFKDwBQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
