kind: Secret
ansible_user: ENC[AES256_GCM,data:Gazr3meSwQ==,iv:kmCrQrJsAEFzftXeFXkR3BozqHXkH4+sP0BWW6vw2+0=,tag:B8UzcurDVUZVzALG6KgGKg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cJvP4DQ3T1zz57XJ,iv:4QP72En8th079o5H7h1SaE3CwoWs0dGOc40wvZUz698=,tag:zB4LaGsH7FYIHh9oel5qeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ekxGeTV3ZEJiS2IrcE4r
            YkxZN2JqcXJPUTYxUWcwZFlCc1BNMU5MdEhnCnBuQldLTFFFdFNZMG9qd2FSNS9P
            R2RBKzV6YjhGLy8vcTlvSWxXYU4vQ0EKLS0tIEVwL1NkU0ZLaktiZSs3bElZVE16
            ODVlMHgxcHZHSW1TSXIzak9xUmJJYWcKVzK1eylk+ibCDU6mmExexFISFmP4Ncpl
            9+jWukd4cH8dg8k0ybq7Y1Drd9GgJUidgIeCRKqkdPhvnxMnfAmmEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T11:17:11Z"
    mac: ENC[AES256_GCM,data:PNnZw9cnlMNogMhtCebR4RC5EtbdJ1tTk5FVIvGpv54wuinywohQ1PTn22PHJ6uO3HIJzjKoQjMeGjVJZojd9gPJANsd4Itn7l+EU215V1RZDFEJ91PmdJmKYI0Fsy2KcUhBebFVQHbjClEQ1o3FUu0hBN8cZcQGyIaJ5C7mCN4=,iv:UurySmKVYB6C7QoKNikIfkeWAEv7K2RP6cKWZGzQ/+0=,tag:URfaZa10/bNBrF1DGk8DTg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
