kind: Secret
ansible_user: ENC[AES256_GCM,data:o+GsCWnNAg==,iv:QGO8/gKJPMhXb+2CKawcJucxdWXIcjY8SXcot/LWZxI=,tag:GUMfjbfXGB9BRqi4J3lPPg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dZMT4U/nd5yIcXt9,iv:Cg1ZaMNFUTnICJ3gDjyd7vtJI58bhIZ6LubuiQFZlBY=,tag:HunFt/dTRvbdmKCOC/AxXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRHJ3T1prTy9mOUxMSTRh
            SGoyVTBZdHBxRHc3Z3NHRWlDWS91MUJUVUFJCk4xUWlFZlV5S05EM1hCbWhvS2Qv
            b3ZDR3dzYWJUeFJ3ZmVBbzc3ZWRJVE0KLS0tIDNQTEs5d0IyVjdMY0NLTGdoMENV
            dThsd1pTTGczd2orWTVnRGs0cFAxbFkKqY8+2CL1Dal3KNthvvLxrY42oeEiZpV7
            8qIPYclBJsm2iO3MBxygR2+XNlcJYZwM+zvJE1fOpJkOk3Hcku7Zww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T11:17:11Z"
    mac: ENC[AES256_GCM,data:AHpAYLQpYiyboHc5DC8ft98/lTWh1mpbtg6SpKB9KIGRzcfljzwvBwzsXZ8x7q3iPnvT1SOZ7BubeqahoOIWNZYO1KwlaBMvFUo30LrpLmdStMdccpkabStd3oql4ESWvLtWfEC6kBz1+SPt5qpo8yON+EtCHQvsk9IfIPiZwOY=,iv:0UTJMCEQ9Mpzwp0FR8tSLhuJrPsXShFnM7XL0z9X0sY=,tag:RlKp86P7HajJittTlKifIA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
