kind: Secret
ansible_user: ENC[AES256_GCM,data:Fl7KJht2oA==,iv:55xFeOQT6skYsFICna11NkeMBu9KqGpnJV7IB4A10dE=,tag:/chp5p6gi3zYhyd0GqakyQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2QTHdV1a3TsDbO8U,iv:A6GrVMxX81Xxl6CEbOL267mk3VRTmYP3e5kcBodYu/w=,tag:7VGid1tWp1qPyMTXQgaKFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0dKZ0YyUFYrWTlwbys3
            YzJTaWZFaGlNS3Y5bmNkbFBJS0pVMi8rZ2prCnc0Y2hqL1owUkQza0tBTGJOTHRO
            ZS9GanBtWmJud29qMnF0TGpPVE95MWsKLS0tIFd1eXVxSytzenFlend5WHdGZE40
            UHV1ZG04aWV5a0wycElRb0pEZkJtblUKNLyODP60I+0n0XQBx/R3/Oz5plOelWQK
            tGixmhczpM9h8vBuTuSgBZAX8Xa7mqaAlvVa3+iRYVSIgPluuxjW9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T04:26:00Z"
    mac: ENC[AES256_GCM,data:JMCW0LhsXHesQ6YOXiUQBeVvJAst/zmtp6wtLAXWniWYzna2jovTBKcQ6hr5DP9tVXFlhYqe6XbDCtaezXoIo2R43zTgMqIt4hWfspxZEcVLwxiVzjCoN4CcQrAWZD5DBdnOpX31z2AN5kMwyQz1XXH4mBxe62Argnx8pH7tChE=,iv:g5VfqiC2UY7OrW2RQ+LjB1yJyGalN0RC7RLKAlOj9h8=,tag:2Y+r9Omw6IH1boPL3Q7cUA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
