kind: Secret
ansible_user: ENC[AES256_GCM,data:8trhifcjRQ==,iv:Qp/k7U70v4zdtaHcX3W0X4Z/K2XgX26EELGHZO8crRs=,tag:hDAxRCAqUabO+1YJ+cY4CA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:t3jk4URhLF2k4eYD,iv:YD3AWeLdZFZ/bQlATGHskq9LZwkKo+lo1osC3KhDsGM=,tag:+ZABa9CFfx0zCwjwJecXvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM1lWT2pkU3l5ZlNxWVRF
            NktTZ2s3bWcyZC83d3ZoODErcGR1Y1VXUUV3CmgyRjJEaXRUYllNYk9wbitYLytI
            Tm9XYzlkUWpqWHNoZ09ReDZrR1MrYzQKLS0tIG9IR2tWbVRwYzNhUGlhckk1bHZz
            ZmlUZnJibUtZZTVVNlNNZUlkSEE4YXcKPHg0vosdospLwS0/YzbKWwI6NFeQ8Bur
            kLxaPYQ33l2457NDdO+TRMTqhho9F4doH9mErAhzIaYX5JtSzlytWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T04:26:00Z"
    mac: ENC[AES256_GCM,data:mdkD4lCFAtz+HtCgLcjz470wFyyn4iXOzw7uNgkC46wcVSjoI7zVFyhE3EJaC1yI46tZTo+kZbhuzGE1jnYGAcY8QpZNzHn2/hQT8OwrO8zUhsSz1E/m8T5qi0uKIG8ocLcQUqQkiivtDcLQ28A6Vs0GxvD2E9f4yEuCvrJy5MQ=,iv:wsNu6Cd3s+FTP1H0FjJ5iK12L4SGSU5s0XmCK0EzVRY=,tag:rpczjeiBz+IcQa/iY7tngw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
