kind: Secret
ansible_user: ENC[AES256_GCM,data:aqdw7VXB+Q==,iv:BcEUtPd9/cIsvrK3Sw3SZjD9lunaP/I4JJxc9l3G5ko=,tag:QGqVua2QJVBM/jRQ6A/R4w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:aXlZ0c2ZjwlsuYuw,iv:XJYh/pfAc67h4/9O/hOTykJxFdY/NzfowoN4Le7aLl0=,tag:KXDRZvgqFGBIG3x6fK+LFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUXVvRWw2UzRKbGdYZ1Av
            Lys1M212cTBjaCs0Y1g0VVVCMXljUGJVSFJRClU1MWZmLzlTVzhoV2lBYlFwU1Vk
            SE5XdVNPbHV4bGtGZ3owREdCQTdIZmcKLS0tIGd0djZ0dEFjS0xSSWdKUS9taUtz
            Tm51VDdqSXBCdzB3cVFtMHhOZDlpOG8KEWMfYxygEVQkBfTw37x6/tJXYEPvY0ur
            s7DVyR/bonUWTKtkVfGvPRDCXl/ec/I6dJbAldhI6b24rQRYJdFGhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T03:32:17Z"
    mac: ENC[AES256_GCM,data:ZjsHJEdARJDzR+7zYa9U4005oVn1gOeY0yvZLQBuB/tnbeV4gFzhvZfSyEYz4Q8M6FKw/jlcpE29C2eHRgPyl7BAduVWLTmxEPJGT8bdOhbt5WKQ6n6Bul+b1OQOAGnJNPjUgX4C6mdAX4tJCO3emS5O3e0fRf/YTh4QvrnNtns=,iv:PAQbrTvc/My0YZrim4lesJwqKLltSSD6DYz9EbJSvwk=,tag:iZCJp+OChHkP06mYFsR8IA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
