kind: Secret
ansible_user: ENC[AES256_GCM,data:XSynzQhoXw==,iv:CYlTEaz3mZlXSMWNC8BABS7wxhoHRoJSi+xepo4J8hU=,tag:ZhbkriQdbvXt4ILiMMK4ag==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2PS1P8+z5zAxs1mC,iv:2CvRO4fG+o2DnfHeRBeIBuWdGJWsvvqBAqBAWs/eA0I=,tag:cqxgaB0sswaNznOKObI5qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTm90S1BRYjhEYVJGbjVq
            bzdPMVFtMFFGUy9IUUh1cXNEMGMvZXBueFVjCnZSRVIycE5vMFZSek9Ha2xNWEFC
            c1NJa3RiazI2NXpMYUY0RWJxcGZNNWsKLS0tIG50K0VlQ2d4VE5rc0lMZjlkQTVp
            RDZrdElmU0U1QUZOTUNBTnk1Yjh1K1kKk5v6yHxEf55nxrP4AMISoIPHig3nMots
            BUs/Wc7mU6iVQSeykPuri+d0QLB15Cv8xQgtE+OrIWuXuW3gP7REgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T04:26:00Z"
    mac: ENC[AES256_GCM,data:vv1bGxWTUOWfY1fehbOmwGYzv1k2fUFr1+60XgaO5wGQeiz4xDmamY61kGjtiWR4NicLiIiIkTLjmjW3DuGuChz67wc4j2z0iT0+7RcJ9M30AOnt6ZkqtFPXu/f4c2XjwOeoatviiroiLIErwqsjvMTdoKSgxuM6o4u0trWgVik=,iv:EZ0UB7dd88KDLQ808Zm6CYooVySuzBqVpbnkyHaNlFI=,tag:qS5RH4sJnR0spO/CMULGyw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
