kind: Secret
ansible_user: ENC[AES256_GCM,data:OsqhqQaWlQ==,iv:PZ4ukbHuMLyvAPi2j07hJlyYQzZFT5q5dnY0a6znxQ8=,tag:1E3MHO4nEHj5BR9G+8+F2A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qRUbmWOeSe8AhT3F,iv:8qckjcKYiMLHMnGPNgOUC/dQyZcguMFfF3w5zWcc6Qs=,tag:BTDRzk5iFIpiPrq3EKeirw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2fa4x3qjhaqn6vzqnxwcu2stud6e5k484csl42uedwllg3p4vrs88xjzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTW1UMEN1YzNoWVYrQnBG
            VWtNZ0NKYjVtU0RVNlZ5QnZWYlVJWVIxUmdBClowVFZCZVZMYzJ1S1IwMWl4Y2Fu
            WVo4MlExY2dRd2d2L1R3RkdrcDQzMlUKLS0tIGp6dDFTNzMyK0xodjB5RlFsVWdp
            a3l0TnIyQWNWV2l5TFRGU3hYUmcrWG8KOdbmKlVPCD3YqjNDiFVH5Ozt7GnKfbaX
            lK6X+5zaC4mDwafC4GGddMN/5qt9Gs2O7sjHqtBgU94WcIS/1k/SWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-11T03:32:17Z"
    mac: ENC[AES256_GCM,data:2dngVLgUMg0cC5vXZY6Dlms6bhL+Ya17BiSxxEkhap0PFYGPmmEVIIH+qH4DynwM8tSJk9cHUmInWa0us12JHpWiXqFrzBMX3xTs77l9iXMuUh5xje3vtB1I8vTgpChCg7Z7d5uPoHF5gocRaqMyOuN7FwBzvVluDlzlXdrQfM8=,iv:AqdDO/guFzjD4k+/W1iPyxMNhN2qM9f179kFNkcOXrc=,tag:JRjR9BPfhp07ZF5YokkU1Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
